### PR TITLE
first stab at isolating network tests (#263)

### PR DESCRIPTION
**Pull request by arderyp**
Updating CircleCI config files to run all tests, but not require network tests for building/publishing tagged releases. Bumping version middle-most.

@mlissner you will want to pull this code down to your machine and execute `python -m unittest discover -s tests/network -v` to make sure that all network tests work with your PACER config.  Go ahead and run `tox` and/or `python setup.py test` while you are at it.

When this branch is merged in, you will want to tag `1.24.00`

(see #263)

### CODE REVIEW

**Comment by arderyp** [comment]
@mlissner I guess we will see if Circle passes with these changes.

Regardless, I am out of pocket from now until Monday evening.

**Comment by arderyp** [comment]
@mlissner, tests passed, but it skipped all the PACER tests that require credentials.  It does this on my machine, as I have no credentials set up, but should Circle have `PACER_USERNAME` and `PACER_PASSWORD` configured?  Has CI historically executed those tests?

**Comment by mlissner** [comment]
Thanks @arderyp. Some of this (like the circleci configs) is a bit over my head, but it all seems to work nicely both in CircleCI and on my local machine, so I think we're in business.

I don't *love* the class-based file names. I might change that eventually to more normal names, but the allure of getting this landed was worth pulling it anyway. CircleCI is running now. Hopefully it'll work!

**Comment by arderyp** [comment]
hmm @mlissner , I had a little more work to do lol, oh well.  Class names can change but must retain "test_" prefix

**Comment by mlissner** [comment]
I figured not much risk I'd break the already broken. Let me know if you want help, otherwise, I'm just hoping to get a version released tomorrow, but I can still do that manually if need be.

**Comment by arderyp** [comment]
let me poke around a little more tonight.  You can cut the release either way tomorrow.  Nothing is broken, we are just not executing PACER tests in Circle because, for some reason, the env variables aren't working... I still need to figure out why.

**Comment by mlissner** [comment]
I think we are actually running them though. If you look at the latest workflows, they failed due to the network tests.

**Comment by arderyp** [comment]
I think there is lots of confusion here, and its not helping that we are commenting both here and on #263.  Since this PR is closed, lets please stop commenting here.  Take it back over to #263

**Pull request merged**
