### PR TITLE
953 Normalize docket_number and case_name in FreeOpinionReport

### PR DESCRIPTION
**Pull request by albertisfu**
This PR addresses issue #953 by standardizing the parsing of `docket_number` in the `FreeOpinionReport`, which previously differed from other reports. This discrepancy was causing inconsistencies in the Docket Number and triggering conflict errors in issue [#3541.](https://github.com/freelawproject/courtlistener/issues/3541)

Now, the parsing aligns with that of the `BaseDocketReport`. Additionally, I observed that the parsing of the `Case Name` in FreeOpinionReport did not match that in BaseDocketReport, occasionally leading to slight differences. Therefore, I adjusted it to use the same parser as `BaseDocketReport`.

- I added local tests for this class. I noticed that this report diverges by returning a list of `FreeOpinionRow` instead of a dictionary containing the parsed data. The data from each row is accessed via properties in CL.
For test purposes, a `metadata` property with a data dictionary was introduced to facilitate JSON serialization.

- Is there a reason to retrieve the docket metadata as properties in CL? Maybe we could standardize this class to return a dict too. It will just require a minor adjustment in CL.

### CODE REVIEW

**Comment by albertisfu** [comment]
The tests are failing; however, it doesn't seem related to the changes in this PR, as there are also other PRs where they've failed [today](https://github.com/freelawproject/juriscraper/actions/runs/8509789653). Perhaps a dependency needs to be updated or something similar.

**Comment by mlissner** [comment]
> Is there a reason to retrieve the docket metadata as properties in CL? Maybe we could standardize this class to return a dict too. It will just require a minor adjustment in CL.

No, not that I can think of. I guess we should do that too, because we can. Want to do that and then I'll review this one more time?

**Comment by albertisfu** [comment]
Thanks, I've applied the tweak, so now the `FreeOpinionReport` returns a dictionary containing the metadata instead of properties.

- Added an additional test covering the case where a document belonging to the previous row (case) has some fields empty, and these are filled with values from the previous row.

- This has also been updated and tested in  https://github.com/freelawproject/courtlistener/pull/3942

**Comment by mlissner** [comment]
Great, thank you!

**Comment by mlissner** [comment]
I think we can release this as version 2.6.0. We'll need to update the read me with the breaking change. We were so close to 2.5.100! Oh well!

Want to give that a go, Alberto?

**Pull request merged**
