### PR TITLE
Various improvements to bankruptcy docket parsing

### PR DESCRIPTION
**Pull request by ttys0dev**
Should better handle some newer bankruptcy docket formats.

### CODE REVIEW

**Comment by mlissner** [comment]
@ttys0dev welcome back! Glad to see your name around here again.

I took a quick look and it seems generally OK, but I'll leave it to Alberto to do a more careful review.

Thank you!

**Comment by albertisfu** [comment]
I reviewed this in detail, and it looks great.

I noticed that these changes add support for properly parsing bankruptcy docket sheets with attachments, so I’d recommend incorporating at least one test to cover those changes.

Here are some examples I used to better understand the changes.

[vawb.txt](https://github.com/user-attachments/files/16698628/vawb.txt)
[waeb.txt](https://github.com/user-attachments/files/16698629/waeb.txt)

**Comment by ttys0dev** [comment]
Added those as tests, also bumped minimum python version to `3.9` since `3.8` is pretty much deprecated and doesn't support `removeprefix`.

**Comment by mlissner** [comment]
LGTM, thank you!

**Pull request merged**
