### PR TITLE
Add scraper for nevada court of appeals (nevctapp).  Fixes #60.

### LINKED ISSUE #60: Add scraper for nevada court of appeals
Looks like an easy subclass of nev_p.py, but it's actually a court that I don't think we have in CourtListener yet. Been a long time since that happened, so:
- Need to decide what to call this jurisdiction. Probably nevctapp? I can't find any references to it in Blue Book v 19.
- Need to find notes on how to add this to CourtListener, and it's possible we'll need to re-jigger the order of the courts in the modal (this, alas, is done manually).

Anyway, worth doing, since it's not every day we have a new jurisdiction.

### PR DESCRIPTION
**Pull request by janderse**
It appears that only unpublished opinions are available.

### CODE REVIEW

**Comment by mlissner** [comment]
Sorry for the delay looking at this, @janderse. I think you can get the published ones here: 

https://nvcourts.gov/Supreme/Decisions/Advance_Opinions/

Want to add a scraper for that too, then I think this should be good to go.

**Comment by arderyp** [comment]
Whats up with the forced push here?  I don't see the commit in our main master branch, am I missing something?

**Comment by mlissner** [comment]
I'm guessing @janderse meant to force push to his own branch or fork. The good news is he doesn't know how to tag releases! (Mostly kidding.)

I'll review the commits and @janderse, we can talk about this in our weekly meeting. 

Thanks for highlighting this, @arderyp.

**Comment by janderse** [comment]
I did a force-push on my own fork in order to sync up with freelawproject/juriscraper.  It shouldn't have affected freelawproject.  Looks like it caused this very old pull request to be closed automatically which is fine.

**Comment by arderyp** [comment]
thanks for clarification, I couldn't really figure out what was going on

**Comment by mlissner** [comment]
> I couldn't really figure out what was going on

I'm not so sure either, actually. Github makes this look pretty confusing, but I don't see any commits to master from @janderse, which seems good. 

Jon, your branch seems to be even with ours. Did this PR somehow get merged without review?

**Comment by mlissner** [comment]
Looks like the code here isn't merged into master yet: https://github.com/freelawproject/juriscraper/compare/2ea4f7ed8075783b0ecab9e0110312b6d91b6ae6..3c5c1d1e7514778a2099dca8044eacd9031b692f

**Pull request closed without merging**
