### PR TITLE
540 Fixed index error when processing docket uploads

### PR DESCRIPTION
**Pull request by albertisfu**
Checking #540 I found that this error is caused by two issues:

- We've been receiving many uploads for a case that seems closed: https://ecf.canb.uscourts.gov/cgi-bin/DktRpt.pl?531591
  The files uploaded only contain RECAP links:
Screen Shot 2022-12-16 at 15 47 39

  So when processing this upload the `IndexError` error is raised. 
I didn't add code to ignore this error, should we ignore these bad uploads?  or we should check it from RECAP extension first? 

- The other issue is related to some docket uploads from courts like `jpml` and `pamd`, these uploads contain long `scripts`. 
  So that the error is raised after `strip_bad_html_tags_insecure` method is applied. This method uses `Cleaner()` to remove unused HTML content and the problem happens specifically when removing scripts. If the `script` tag contains a `<` followed by a non-space char (e.g: `<ca.length`) `Cleaner()` removes all the following HTML, so the HtmlElement object is truncated and it's not a valid docket report.

  To solve it, I tweaked `strip_bad_html_tags_insecure` to receive the HTML as a string so we can remove the scripts content using regex when `remove_scripts=True`, then when removing the `script` tags there is no truncation problem.

- I was also checking [#2243](https://github.com/freelawproject/courtlistener/issues/2243) (I'll add more comments on that issue about other findings.) and I added a new error string to validate Email notifications:
  `This is an announcement e-mail message generated by Court action through the CM/ECF system. `
That belongs to this kind of notification that doesn't contain docket entries:
Screen Shot 2022-12-16 at 10 29 37

### CODE REVIEW

**Comment by albertisfu** [comment]
Thanks for your comments!

> I thought we handled that gracefully. In any case, this should be handled by Juriscraper, not the extension. Even on closed dockets like this, there are filings and there can be useful party information. For reference, this is what I see when I load the docket (seems like something we should parse):

Yes, in fact, we can parse properly the closed docket you mentioned.
I did a test and it was properly processed: https://www.courtlistener.com/admin/recap/processingqueue/7347674/change/

The problem is that we are also receiving something that might be bad HTML files for the same `pacer_case_id`, like this example:
https://www.courtlistener.com/admin/recap/processingqueue/7331356/change/

Since the file uploaded only contains RECAP links:
```
<head>
  <title></title>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
</head>
<body style="cursor: wait;"><table><tbody><tr><div class="btn-group" id="recap-action-button"><a class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-spinner fa-spin recap-btn-spinner-hidden" id="recap-button-spinner"></i> RECAP Actions<span class="caret"></span></a><ul class="dropdown-menu"><h2 class="dropdown-header" id="action-button-dropdown-header">CourtListener</h2><li id="view-docket-button"><a href="https://www.courtlistener.com/recap/gov.uscourts.canb.531591/" target="_blank">View this docket</a></li><div class="recap-dropdown-divider"></div><li><a href="javascript:void(0);" id="refresh-recap-links" role="button">Refresh RECAP Links</a></li></ul></div></tr><tr></tr></tbody></table></body>
```
So that's why those uploads are failing since it's not a valid docket page.


**About the other problem related to script tags.**

I've tried to remove script tags using the `tree`,  seems that the issue not only happens when removing scripts using the `Cleaner` but when parsing the bad script element per se.

e.g applying something like this:

```
script_tags = tree.xpath( "//script[@type = 'text/javascript']")
for script in script_tags:
    script.text=""
```
When the script tag doesn't contain a `<` followed by a non-space character, the script content is properly removed.
But if it contains the `<` followed by a non-space character you can see the result in the second example, the script content is partially removed but it creates a bad "tag" based on the illegal content.
```
<script type="text/javascript"></script>

<script type="text/javascript"><ca.length i var c="ca[i];" while if return c.substring>
```
That's why when using the `Cleaner` method all the remaining HTML is also removed since the parser can't find a `</script>` tag.

I think this issue might be related to the [HTML using illegal expressions](https://www.w3.org/TR/html401/appendix/notes.html#notes-specifying-data) within script tags, so lxml is not able to parse them properly.

I also tried to use BeautifulSoup's parser `lxml.html.soupparser` instead of `html5parser` and it seems to work well to remove scripts but it breaks some other tests since the resulting HTML is not exactly the same as the `html5parser` version.

So for now the only way it works to solve this issue is by using the regex substitution to strip script tags before parsing the tree.

I added a new test that uses <script></script> tags instead of <script type="text/javascript"></script> and also it works fine.

Let me know what you think.

**Comment by mlissner** [comment]
> So that's why those uploads are failing since it's not a valid docket page.

Got it. It's a bit odd that we're getting these, but I guess we should make the code work when we do, rather than fail like it does now. **You didn't fix this in this PR yet, right?** 

> So for now the only way it works to solve this issue is by using the regex substitution to strip script tags before parsing the tree.

Well, I was afraid of that. Too bad. I wish we had something closer to how browsers worked. If browsers can render this properly and run the code, then lxml's html5 parser should work too. Ah well. Regex it is! 

>

**Comment by albertisfu** [comment]
> Got it. It's a bit odd that we're getting these, but I guess we should make the code work when we do, rather than fail like it does now. You didn't fix this in this PR yet, right?

Yeah, I haven't added a fix to ignore these odd uploads, I just wanted to be sure we should just ignore them. So I'll add code in this PR to ignore these uploads.

Thanks!

**Comment by albertisfu** [comment]
I've added a new method within `BaseDocketReport` that checks if the HTML is not an odd upload that only contains recap links. 

If the HTML contains recap links, it's also checked that there is additional content to parse. Since the odd HTML upload only contains the `recap-action-button` element and a table with empty rows.

Let me know what you think.

**Comment by mlissner** [comment]
Cool. Your solution is fine, but something to remember is that this is a library that others may also use, so we generally want to be careful not to put CL or RECAP-specific code in here. I guess another way to fix the problem would have been to check if it had content, or to put a try/except around a different part of the code, but like I say, this is fine for now (it doesn't hurt people that use this outside the RECAP world, at least).

**Comment by albertisfu** [comment]
Great, thanks for the advice! I'll think of a different way to handle this without involving RECAP or CL-specific code. So we could change it in the future.

**Pull request merged**
