### PR TITLE
check environment to skip slowness errors

### PR DESCRIPTION
**Pull request by umeboshi2**
Please don't blindly accept this request.  The readme should probably updated.  I am also interested in diminishing the errors into warnings, where y'all can promote the warnings to errors when calling python.

### CODE REVIEW

**Comment by mlissner** [comment]
This still has some tweaks to go, right?

**Comment by umeboshi2** [comment]
Most certainly!  It's basically a request for comments so that I know what to write.

**Comment by mlissner** [comment]
How about renaming `IS_TRAVIS` with `WARN_SLOW_SCRAPERS` and then depending on that variable either print a warning or throw an error?

**Comment by umeboshi2** [comment]
Sounds good.  I wasn't sure if ```IS_TRAVIS``` was being used for other reasons in the tests.  It looks like I would have to have both a Warning and an Exception class to do that.  I'll figure out how to do that this evening.

**Comment by umeboshi2** [comment]
I'm not sure if you want to use the "always" filter, rather than the "default" filter, but it helps to identify each slow scraper in the tests.  I made two warning classes where one tells the user/tester that the slowness is  potential error.

**Comment by mlissner** [comment]
Yeah, I think we want a warning for each slow scraper as it happens.

**Comment by umeboshi2** [comment]
Cool, it's implemented.  There is a simple slow warning and another slow warning where the user/tester is informed that the scraper is too slow and the warning is "potential error."

**Comment by mlissner** [comment]
Thanks!

Mike Lissner
Executive Director
Free Law Project
https://free.law

**Comment by umeboshi2** [comment]
@mlissner the travis output looks pretty nice.  Slowness warnings clearly displayed in test log for each slow scraper.

https://travis-ci.org/freelawproject/juriscraper/builds/475046768#L1294

**Comment by mlissner** [comment]
Very nice!


Mike Lissner
Executive Director
Free Law Project
https://free.law

**Pull request merged**
