### PR TITLE
Add Scraper for S. Carolina Ct. of Appeals

### PR DESCRIPTION
**Pull request by varun-iyer**
Very similar to S. Carolina Supreme Court; only the URL was changed.

### CODE REVIEW

**Comment by mlissner** [comment]
If this is only a URL change, could you do this by extending the Supreme Court object instead of duplicating it?

**Comment by mlissner** [comment]
(There are many examples of this in the code, if you poke around. Just look for a really small filesize and you should find some, I bet.)

**Comment by varun-iyer** [comment]
That makes a lot more sense -- done.

**Comment by mlissner** [comment]
This is great, thank you! How do we get more contributions from you?

**Comment by varun-iyer** [comment]
I'm really interested in the project and I'm happy to contribute in any way I can. I was just going off the TODOs in the wiki to start with, is there a specific task that I should contribute to?

**Comment by mlissner** [comment]
I think I'd defer to @arderyp who mostly maintains the court scrapers, but we should get you invited to our slack group so we can chat more there. Send me an email? mike@free.law?

**Comment by arderyp** [comment]
For the most part, I monitor the daily report (you'll see this once you join slack) and fix newly broken scrapers.  There are a few broken scrapers that are failing on that report that actually work, but are simply failing because the court is blocking our scraper.  These you can ignore for the time being, since @mlissner is working through calling the courts to stop the blocking.  The scrapers in question all have seperate issues logged for them with the `scraper blocked` tag.

I can't think of anything off the bat other than monitoring that report.  There is a subsection of the report called "old problem courts" and "new problem courts".  Those titles are somewhat misleading because many of the entries in those sections aren't actually "problematic".  Courts land in those sub-sections because we haven't discovered any new opinions from them recently.  Some  of those courts publish very infrequiently, so we haven't found anything because nothing new has been published (so, not actually "problematic").

Every now and then I comb through those "old/new problematic courts" to see wheather they actually haven't published anything recently--if so, ignore it--or if they have changed their site and have been publishing, but we simply haven't been catching the new data due to the site changes.  So, once you get access to that report, you could go through that process.

The only other thing that comes to mind is [this](https://github.com/freelawproject/juriscraper/issues/263), or any other issue in the queue.

**Pull request merged**
