### PR TITLE
fix(nebctapp): filter bogus docket, A-XX-XXXX

### PR DESCRIPTION
**Pull request by cweider**
The Neb. Ct. App. posts notes in their weekly announements of memorandum opinions and these have a bogus docket, A-XX-XXXX. Filter these from Juriscraper's intake.

Fixes: #701

### CODE REVIEW

**Comment by cweider** [comment]
@pre-commit, the auto-fix to the court’s weirdo HTML isn’t very helpful!

**Comment by mlissner** [comment]
@flooie if you can take a look at this too, that'd be great.

**Comment by mlissner** [comment]
Oh, and when we merge this, let's clean out any stray items that we see when searching.

**Comment by flooie** [comment]
Thanks @mlissner @cweider

**Comment by flooie** [comment]
@cweider this looks good to me.

**Comment by flooie** [comment]
2^8

**Comment by flooie** [comment]
I was going to wait to bump juriscraper before I did it to make sure we didnt add any more after the fact.  but I might as well now and later

**Pull request merged**
