### PR TITLE
feat(state): Remove Maine

### PR DESCRIPTION
**Pull request by flooie**
Comment out maine to disable scraping it

### CODE REVIEW

**Comment by mlissner** [comment]
I thought we were going to keep Juriscraper the same and disable it another way in CourtListener, no?

**Comment by flooie** [comment]
We were - but thats not how the system is set up.  This only stops it from running the Maine tests but you can still use it to call Maine in juriscraper.

**Comment by mlissner** [comment]
Sorry, do you mean that commenting it out stops the tests from running, but that you can still manually import the scraper and use it if you want to (even with it commented out), so you commented it out to stop the tests from running?

**Comment by flooie** [comment]
No, commenting it out will also stop the scraper from running in tests, but commenting it out will also stop it from being included in courtlistner.  our `has_opinion_scraper` code and `is_active` code has nothing to do with whether it will run on `cl_scrape_opinions`

the simplest solution is just to comment it out of the init file

**Comment by mlissner** [comment]
OK, got it.

**Comment by mlissner** [comment]
I found a middle ground: 

https://github.com/freelawproject/juriscraper/blob/main/juriscraper/opinions/united_states/state/__init__.py#L75-L82

**Pull request merged**
