### PR TITLE
feat(RI): Update Supreme Court for Rhode Island

### LINKED ISSUE #428: Fix opinion scraper ri_p
Sentry Issue: [COURTLISTENER-1YS](https://sentry.io/organizations/freelawproject/issues/2813147079/?referrer=github_integration)

```
IndexError: list index out of range
  File "cl/scrapers/management/commands/cl_scrape_opinions.py", line 336, in handle
    self.parse_and_scrape_site(mod, options["full_crawl"])
  File "cl/scrapers/management/commands/cl_scrape_opinions.py", line 305, in parse_and_scrape_site
    site = mod.Site().parse()
  File "juriscraper/AbstractSite.py", line 130, in parse
    self._process_html()
  File "juriscraper/opinions/united_states/state/ri_p.py", line 47, in _process_html
    case = self.extract_case_from_rows(tr1, tr2)
  File "juriscraper/opinions/united_states/state/ri_p.py", line 52, in extract_case_from_rows
    docket = row1.xpath("./td/a/text()")[0]
```

### PR DESCRIPTION
**Pull request by flooie**
PR Resolves #428 

Use JSON response in the ASPX request
to avoid the crud in the previous scraper

### CODE REVIEW

**Comment by mlissner** [comment]
I'll await tests before review.

**Comment by flooie** [comment]
Yes. I did see that.

**Comment by flooie** [comment]
I was technically waiting to fix the tests before requesting your review.  @mlissner - but its all yours now.

**Comment by mlissner** [comment]
I didn't read too carefully, but it looks like a simple enough fix, thanks.

**Pull request merged**
