### PR TITLE
feat(tax): implement dynamic backscraper

### PR DESCRIPTION
**Pull request by grossir**
Helps solve #970

Also, add secondary case.get("judge") in case "signedJudgeName" is not found

### CODE REVIEW

**Comment by quevon24** [comment]
@grossir the page seems to have a throttling policy and can't make more than 15 requests per minute and for some reason it gets the throttling exception on the 8th request:

`{'message': 'you are only allowed 15 requests in a 60 second window time', 'type': 'ip-limiter'}
`

With this request params:
`{'dateRange': 'customDates', 'startDate': '06/17/2021', 'endDate': '07/16/2021', 'opinionTypes': 'MOP,SOP,TCOP'}`

I ran it with this command: 
`python sample_caller.py -c juriscraper.opinions.united_states.federal_special.tax -vv --backscrape --backscrape-start=11/19/2020 --backscrape-end=01/25/2022`

We could simply divide the backscraper range in two but I found this interesting, maybe their throttling policy is wrong.

**Review by quevon24 — CHANGES_REQUESTED** [review]
@grossir the page seems to have a throttling policy and can't make more than 15 requests per minute and for some reason it gets the throttling exception on the 8th request:

`{'message': 'you are only allowed 15 requests in a 60 second window time', 'type': 'ip-limiter'}
`

With this request params:
`{'dateRange': 'customDates', 'startDate': '06/17/2021', 'endDate': '07/16/2021', 'opinionTypes': 'MOP,SOP,TCOP'}`

I ran it with this command: 
`python sample_caller.py -c juriscraper.opinions.united_states.federal_special.tax -vv --backscrape --backscrape-start=11/19/2020 --backscrape-end=01/25/2022`

We could simply divide the backscraper range in two but I found this interesting, maybe their throttling policy is wrong.

**Comment by grossir** [comment]
I don't get the rate limit. This scraper makes 1 request for the results page, then a request for each result, to get the "download_url". I have ran the scraper many times in a row and it won't trigger the rate limit, with 30 results, that's 31 requests in less than a minute.
I am using an IP in the US, maybe that's the reason?

On the other hand, in case the rate limit is actually triggered on the server, apart from splitting the range, maybe a `time.sleep` in `_download_backwards` may make it work

**Comment by mlissner** [comment]
Seems like putting a `time.sleep` in the backscraper would be a simple and effective trick. Nothing to lose. :)

**Review by quevon24 — APPROVED** [review]
I tried with a VPN but it also failed, with sleep the message no longer appears. Time to merge it 👌

**Comment by mlissner** [comment]
Nice one guys, thank you both!

**Pull request merged**
