### PR TITLE
Remove Selenium

### PR DESCRIPTION
**Pull request by flooie**
Selenium is ugly and slow... and not necessary. 

This is a DRAFT PR with selenium removed from every scraper. 

I believe it has one final failing test that needs to be cleaned up.

### CODE REVIEW

**Comment by flooie** [comment]
@mlissner @arderyp 

I hope this is kosher.  But I've removed selenium from juriscraper.  I thought it would be nice to remove it as a dependency from juriscraper and courtlistener.

**Comment by arderyp** [comment]
this i too much for me to digest, but I know that removing the selenium dependency is definitely a goal we've had for a while, so as long as functionality remains and the scrapers still work as expected, then this seems like a good idea to me.

Related issues:
- #333 
- #280 
- #93 
- #74 

Related PRs:
- #380 
- #308

**Comment by flooie** [comment]
@arderyp thanks for the comments.  It didn't actually take much work and it works pretty well with the opinionsitelinear class we are using now.  Testing were easy to update and there were just a few scrapers to work on.

**Comment by mlissner** [comment]
Closing this. Bill is going to pull this into smaller, more manageable PRs.

**Pull request closed without merging**
