### PR TITLE
feat(ky): dynamic backscraper

### PR DESCRIPTION
**Pull request by grossir**
Solves #972

Changed scrapers to use 'OpinionSearchPortal'
Leaving development aside for now, site is failing periodically

Edit: site is stable now

### CODE REVIEW

**Review by quevon24 — COMMENTED** [review]
I have a few questions, i took a look to the issue, you mention that there are 626 documents in the court page, i tried to run the scraper but the backscraper only returns 20 items:

`python sample_caller.py -c juriscraper.opinions.united_states.state.ky -vv --backscrape --backscrape-start=12/27/2017 --backscrape-end=05/17/2020`

I'm not entirely sure about this, but i think it only returns 20 items and can't be paginated in the api, only in the search portal, right?

I saw that it doesn't generate page ranges like the other backscrapers to go back and get old documents.

the back_scrape_iterable iterable only has: `[(datetime.datetime(2017, 12, 27, 0, 0), datetime.datetime(2020, 5, 17, 0, 0))]`


What am I missing? to take more into account those details when doing the reviews and not bother you with so many questions 😅

**Comment by flooie** [comment]
A couple comments about Kentucky.  

I see you collecting disposition - but I dont see it reflected in the testing file.

**Comment by grossir** [comment]
Updated following your advice @flooie , please check again
I am still using that `get_json` function to avoid modifying the `self.url`, given that such url is used for checking the hash
https://github.com/freelawproject/courtlistener/blob/11aaefe029855a3942c669f0ee4f69d010bf5d49/cl/scrapers/management/commands/cl_scrape_opinions.py#L244

**Comment by flooie** [comment]
Also - what do you think about using `normalize_judge_string` to make the judge names not all upper case?

**Comment by flooie** [comment]
Thanks for slogging thru this one with me @grossir - lots of great changes and lots of great new data we will be able to take advantage of moving forward

**Pull request merged**
