### PR TITLE
Update version pinned dependencies

### PR DESCRIPTION
**Pull request by ttys0dev**
Lets update these to their latest versions.

### CODE REVIEW

**Comment by mlissner** [comment]
Did you read *these* release notes?

**Comment by ttys0dev** [comment]
Looked to be bug fixes from what I could tell.

**Comment by ttys0dev** [comment]
@mlissner does this look good to merge?

**Comment by mlissner** [comment]
Hm, I'm fine upgrading most of these, but selenium tends to have a lot of broken pieces. We can give it a shot, but I suspect it'll break things.

**Comment by ttys0dev** [comment]
> We can give it a shot, but I suspect it'll break things.

I guess we need a new release here as well? Or are there some additional tests that we should run before hand?

**Comment by ttys0dev** [comment]
Tests in courtlistener pass with updated selenium as well, just needed to make [this tweak](https://github.com/freelawproject/courtlistener/pull/2757#discussion_r1203165029).

**Comment by mlissner** [comment]
I think it should be fine. I *think* we use Selenium in three ways:
 - tests, here
 - tests in CL
 - to scrape, using a headless scraper defined in k8s as a pod (or perhaps a deployment)

So monkeying with it here should affect anything and I don't think it even needs a release.

**Comment by ttys0dev** [comment]
> I don't think it even needs a release.

Well if we don't have a release we have to use a git dependency in courtlistener like [`{git = "https://github.com/freelawproject/juriscraper.git", branch="main"}`](https://github.com/freelawproject/courtlistener/pull/2757/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711R108) in order to use the newer selenium version.

**Comment by mlissner** [comment]
I don't think so. CL sets a variable that means it uses a remote selenium driver instead of the one that's part of Juriscraper. Check out `WEBDRIVER_CONN`.

**Comment by ttys0dev** [comment]
> Check out `WEBDRIVER_CONN`.

Oh, that's for using a remote webdriver server I think, I'm just referring to updating the python client library version.

**Comment by mlissner** [comment]
Hm, right, OK. @albertisfu could you do a release of Juriscraper when you get a sec, please?

**Comment by albertisfu** [comment]
Sure, `Juriscraper 2.4.8 `release is ready.

**Pull request merged**
