### PR TITLE
feat(scrapers) New scraper for DC Circuit unpublished cases

### PR DESCRIPTION
**Pull request by ikeboy**

### CODE REVIEW

**Comment by mlissner** [comment]
Beautiful, thank you.

**Comment by mlissner** [comment]
Hm, looks like Black is failing. Can you check?

**Comment by ikeboy** [comment]
It passed black when I originally committed. I'll double check.

**Comment by ikeboy** [comment]
would reformat /github/workspace/juriscraper/opinions/united_states/state/ohio.py
would reformat /github/workspace/juriscraper/opinions/united_states/state/nyappterm_1st.py
would reformat /github/workspace/juriscraper/opinions/united_states/state/wash.py
would reformat /github/workspace/juriscraper/opinions/united_states_backscrapers/federal_appellate/ca10.py
would reformat /github/workspace/juriscraper/opinions/united_states_backscrapers/federal_appellate/cadc.py
would reformat /github/workspace/juriscraper/opinions/united_states_backscrapers/federal_appellate/ca5.py
would reformat /github/workspace/juriscraper/opinions/united_states_backscrapers/state/ill.py
would reformat /github/workspace/juriscraper/oral_args/oral_argument_template.py
would reformat /github/workspace/juriscraper/oral_args/united_states/federal_appellate/ca8.py
would reformat /github/workspace/juriscraper/oral_args/united_states/federal_appellate/ca9.py
would reformat /github/workspace/juriscraper/pacer/case_query_advanced.py
would reformat /github/workspace/juriscraper/pacer/rss_feeds.py
would reformat /github/workspace/juriscraper/pacer/docket_report.py
would reformat /github/workspace/setup.py
would reformat /github/workspace/tests/local/test_DocketParseTest.py
would reformat /github/workspace/tests/local/test_JudgeParsingTest.py
would reformat /github/workspace/tests/local/test_PacerPossibleCaseNumbersTest.py
would reformat /github/workspace/tests/local/test_ScraperExampleTest.py
would reformat /github/workspace/tests/local/test_ScraperSpotTest.py
would reformat /github/workspace/tests/network/test_PacerMobileQueryTest.py
would reformat /github/workspace/tests/network/test_PacerSessionTest.py
would reformat /github/workspace/tests/network/test_PacerShowCaseDocApiTest.py
Oh no! 💥 💔 💥
30 files would be reformatted, 365 files would be left unchanged.

This is your new version of black, I think.

**Comment by mlissner** [comment]
Yep, that'd explain it. Do you have bandwidth to handle the upgrade? It's pretty simple. Just run it, commit it, and then add a line to the .git-ignore-refs file to ignore the previous commit? If you're busy, I can go for it too.

**Comment by ikeboy** [comment]
Yeah, I'll try

**Pull request merged**
