### PR TITLE
Added tests for docket iquery pages

### PR DESCRIPTION
**Pull request by albertisfu**
Working on adding the endpoint and process Docket iQuery Pages https://github.com/freelawproject/recap/issues/251

Seems that there is no need to add a new Report since Docket iQuery pages can be parsed by `DocketHistoryReport`. Added tests using Docket iQuery pages for multiple courts to confirm it.

### CODE REVIEW

**Comment by mlissner** [comment]
I feel like I'm missing something, but shouldn't these be parsed by the `CaseQuery` parser?

**Comment by albertisfu** [comment]
Yeah, you're right, these tests belong to `CaseQuery,` so I just move these new tests to the `case_queries` folder.

**Comment by mlissner** [comment]
Huh. OK. Merging because why not, but I'm a bit confused about why? We already have a bunch of tests for case_queries. Do these add something more?

**Comment by albertisfu** [comment]
Thanks, these are new tests I collected from recent queries in PACER, but no they don't add something new, next time I'll just add tests that add something different than the existing ones.

**Pull request merged**
