### PR TITLE
Make docket history report parser more robust

### PR DESCRIPTION
**Pull request by ttys0dev**
Should handle some newer history report formats better.

### CODE REVIEW

**Comment by mlissner** [comment]
Looks OK, but can you include a test too, to prevent regressions?

**Comment by ttys0dev** [comment]
Hmm, I think bankruptcy reports from pacer instances on [version 1.7.1.1](https://court-version-scraper.fly.dev/) with the checkbox were all broken, have any recent ones can add as tests?

**Comment by mlissner** [comment]
Shouldn't be hard to get something, should it?

**Comment by ttys0dev** [comment]
Any existing uploads? Think I'm out of free credits.

**Comment by mlissner** [comment]
Gotcha. @albertisfu, can you help grab something recent from one of the courts with this version number?

**Comment by albertisfu** [comment]
Here are some recent examples from courts using version 1.7.1.1:

[wyb_1.txt](https://github.com/user-attachments/files/16714193/wyb_1.txt)
[dcb_1.txt](https://github.com/user-attachments/files/16714194/dcb_1.txt)

However, I couldn't find a report that displays the checkbox, and these examples don't seem to have the parsing issue.

I also checked one from version 1.7.1.2, which also seems fine:
[casb_1.txt](https://github.com/user-attachments/files/16714192/casb_1.txt)

Additionally, I reviewed recent bankruptcy docket history reports with failed uploads, and they failed for a different reason, as the parsing was correct without the tweak from this PR.

Any additional instructions that could help me find an example with the checkbox?

**Comment by ttys0dev** [comment]
> I also checked one from version 1.7.1.2, which also seems fine:
> [casb_1.txt](https://github.com/user-attachments/files/16714192/casb_1.txt)

This one is bugged without this change to the parser, long description fails to parse, added it as a test.

> Any additional instructions that could help me find an example with the checkbox?

By checkbox I meant the include descriptions checkbox, not a checkbox on the actual page.

**Comment by albertisfu** [comment]
> This one is bugged without this change to the parser, long description fails to parse, added it as a test.

Oh yeah, you’re right. I didn’t see that the long description failed to be parsed. So that example is correct.

**Comment by mlissner** [comment]
I'm trying to follow here and I'm not sure I understand, so I'll duck out. Alberto, please merge when ready! :)

**Comment by albertisfu** [comment]
Yeah, this looks great, merging!

**Pull request merged**
